UMIPs/umip-3.md

The github rendering of this UMIP was very difficult to read because markdown requires two line breaks to end a paragraph.
I've also added one additional commit that will be included in this proposed upgrade.

Reformat and update UMIP3

---

UMIPs/umip-2.md

Filled in the section that requested ENG input.
I also added line breaks to the UMIP to cap the line length in the markdown, making the text easier to review and read in its raw form.
I also reformatted the title section to include line breaks so the rich text is easier to read.

Add ENG input to UMIP-2

---

UMIPs/umip-1.md

Context: https://github.com/UMAprotocol/protocol/pull/1585#issuecomment-641482175

Move Final to before Approved

---

UMIPs/umip-5.md

Creating a new UMIP for COMP/USD based off the UMIP for ETHBTC.  I believe this umip is ready for distribution and community comments.

New umip for COMP/USD Price ID

---

UMIPs/umip-5.md

includes a specification for how to calculate this identifier in the pre-coinbase-pro era.

revise technical specification

---

UMIPs/umip-draft_btcdom_altdom.md

Hey UMA! Here is our draft UMIP for adding BTCDOM and ALTDOM as price identifiers for coin market dominance. Let us know your thoughts and feedback on the draft. Thanks!

UMIP - Add BTCDOM and ALTDOM as price identifiers

---

UMIPs/umip-29.md

As discussed with Pascal offline, merging in the suggested outstanding comments for editing the language around alternative data sources as well as changing the result processing to match the `Implementation` section.

fix(umip-29): Update language for alternative data sources and result processing specification

---

UMIPs/umip-33.md

After speaking with Sean, we realized price feeds aren't going to be able to natively support the ETH to USD normalization. We chose to submit an amendment to change the source to use the Bitfinex AMPLUSD price as it is high volume. Let me know if there are any questions regarding the proposed change.

Change price feed from Uniswap to Bitfinex

---

UMIPs/umip-51.md

This PR updates UMIP-51 to use the highest volume markets available, clarifies the voting implementation and fixes broken links. @OpenDAO-Logan can you take a look at these?

Make suggested content updates to UMIP-51

---

UMIPs/umip-35.md
UMIPs/umip-39.md
UMIPs/umip-49.md

This PR edits the Badger LP price identifiers to clarify the implementation explanations.

Fix Badger Price Identifiers

---

UMIPs/umip-62.md

Change the rounding specification to 9 decimals to reduce precision-based disputes on funding rate proposals.
Also removes any steps around the Token Scaling Multiplier. This scaling multiplier is a deployment parameter but is used to define the starting CFRM, so it is accounted for by using the CFRM.

Change rounding specification and remove token scaling multiplier

---

UMIPs/V2migration_KPI_Aragon.md
UMIPs/umip-79.md

Because of the time pressure were I forced to fill it out as fast as possible. I'm sure it isn't correct. This is clearly not the way I would have liked to open this PR. But a misunderstanding was resulting in this situation.

Aragon KPI UMIP

---

UMIPs/umip-draft_vti_priceID.md

The DVM should support price requests for the [Vanguard Total Stock Market ETF](https://investor.vanguard.com/etf/profile/overview/vti) (VTI), a highly diversified exchange-traded fund that aims to track the US stock market as a whole.

Add uCRSPTMT_SEP21 price identifier

---

UMIPs/omnibus_3_priceids.md

- Update to align with recently passed PI UMIPs
- Add specific examples of markets to use for each coin
- Add specific examples of using the subgraph, where applicable

Update omnibus price id UMIP

---

UMIPs/omnibus_priceid_2.md

- BASKUSD
- USDBASK
- MPHUSD
- USDMPH
- APWUSD
- USDAPW
- SNOWUSD
- USDSNOW
- NDXUSD
- USDNDX

Add Price Identifier Omnibus

---

UMIPs/umip-113.md
UMIPs/umip-114.md

Update status and file names for UMIPs 113-114

---

UMIPs/umip-115.md

Update status and file name for UMIP 115

---

UMIPs/omnibus-3-price-identifier.md

Add Omnibus 3 price identifier UMIP

---

UMIPs/umip-116.md
UMIPs/umip-117.md
UMIPs/umip-118.md

Assign numbering for UMIPs 116-118 and update headers

---

price-identifier-template.md

Split out Technical Specification section for price identifier template

---

UMIPs/umip-121.md

Update status and file name for UMIP 121

---

UMIPs/umip-123.md
UMIPs/umip-124.md

Update headers and numbering for UMIPs 123-124

---

Implementations/stakedao-tvl.md

Add StakeDAO TVL Implementation doc

---

UMIPs/umip-125.md

Update headers and numbering for UMIP 125

---

UMIPs/umip-121.md
UMIPs/umip-122.md
UMIPs/umip-123.md
UMIPs/umip-124.md

Update UMIPs 121-124 to approved status

---

Implementations/baskprice-1221.md
Implementations/bdiflip-1221.md

Add BasketDAO KPI options implementation

---

Implementations/smart-alpha.md

This is WIP, requires input from BarnBridge team on SMART pool contract ABI to fetch on-chain data

Add BarnBridge SMART Alpha KPI options implementation

---

Implementations/yel-lp.md

Add YEL LP KPI Options Impmementation

---

Implementations/dfx-tvl.md

Address from here: https://github.com/dfx-finance/contracts

Add TRYB Pool

---

UMIPs/umip-132.md

Update headers and numbering for UMIP-132

---

Implementations/piedao-dough.md

Add PieDAO DOUGH KPI options implementation

---

UMIPs/umip-137.md
UMIPs/umip-138.md

Update headers and numbering for UMIPs 137-138

---

Implementations/gro-tvl.md

Add Gro Protocol TVL KPI options method doc

---

UPPs/upp-update-fees.md

Precise amount of each collateral token matching $1500 should be still calculated and added to this UPP.

UPP increasing final fees to 1500 USD

---

UMIPs/umip-139.md
UPPs/upp-8.md

Update status and hedars for UMIP-139 and UPP-8

---

Implementations/xio-market-cap-rank.md

Add XIO market cap KPI option method doc

---

UMIPs/umip-140.md
UMIPs/umip-141.md

Update status and numbering for UMIPs 140-141

---

Implementations/boba-wagmi-tvl.md

Add Boba WAGMI TVL KPI option method

---

UMIPs/umip-136.md

Use on-chain rate model parameters in IS_RELAY_VALID

---

UMIPs/umip-144.md

Update headers and numbering for UMIP-144

---

collateral-currency-template.md

Update final fee in collateral template

---

UMIPs/collateral-omnibus-9.md
UMIPs/umip-145.md

Collateral Omnibus 9

---

Implementations/volatility-dao-batch-two.md

Add Volatility DAO KPI method for batch 2

---

UMIPs/dom-collateral.md

Add DOM as collateral

---

UMIPs/umip-149.md

Update header and numbering for UMIP-149

---

UMIPs/Add UMA as Collateral Currency to Polygon.md
UMIPs/umip-150.md

Create Add UMA as Collateral Currency to Polygon.md

---

Implementations/boba-wagmi-v1.md

Add Boba WAGMIv1 KPI options implementation

---

UMIPs/umip-151.md

Update status for UMIP-151

---

UMIPs/umip-153.md

Update status and headers for UMIP-153

---

UMIPs/umip-154.md
UMIPs/umip-155.md

Update status and headers for UMIPs 154-155

---

UMIPs/umip-156.md

Update status and headers for UMIP-156

---

UMIPs/umip-158.md
UMIPs/umip-159.md

Update headers and numbering for UMIPs 158-159

---

Implementations/jarvis-lp.md

Update Jarvis KPI Option

---

Add TETU as collateral currency.md
UMIPs/add_tetu_as_collateral.md

**UMIP #**  - tbd
-   **UMIP title:** Add **TETU** as collateral currency 
-   **Author**  Gregory Tumbiola (Tumbiola@gmail.com)
-   **Status: Draft**
-   **Created:**  May 10 2022
-   **Discourse Link:** https://discourse.umaproject.org/t/add-tetu-as-collateral/1722
This UMIP proposes adding **TETU**  in Polygon for use as collateral in UMA contracts.
Tetu 
The addition of this collateral currency offers additional functionality to the UMA protocol and increases the range of contracts that can be built.
To accomplish this upgrade, the following changes need to be made:
-   The **TETU** address **0x255707B70BF90aa112006E1b07B9AeA6De021424** on Polygon needs to be added to the collateral currency whitelist introduced in UMIP-8.
-   A final fee of **100,000** needs to be added for **TETU** …

Create Add TETU as collateral currency.md

---

Implementations/paraswap-volume.md

Paraswap Implementation Doc

---

UMIPs/umip-164.md

Add Thor as collateral

---

Implementations/thorswap-volume.md

Add Thorswap Volume KPI Option

---

Implementations/aggregation-methods.md
Implementations/defillama-tvl.md
Implementations/post-processing-functions.md

Add DefiLlama TVL implementation

---

Implementations/defillama-tvl.md

Update defillama-tvl implementation

---

UMIPs/umip-assert-truth.md

feat: add ASSERT_TRUTH identifier

---

UMIPs/umip-174.md

This is a follow-up proposal for [UMIP-173](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-173.md) setting UMA emission rewards that were initialized to zero.

feat: update uma emission

---

UMIPs/umip-157.md

Handles edge case where a chain is paused

improve: Add language about 0 block ranges

---

UPPs/upp-14.md

Changes proposed in this PR:
- Add UPP to update final fees to 250$
Fixes UMA-1560

feat: add upps to update final fees

---

UPPs/upp-15.md

This UPP is proposing to update Optimism, Polygon, and Arbitrum to include native USDC.

feat: Add native USDC for Optimism, Arbitrum, and Polygon

---

UMIPs/umip-157.md
UMIPs/umip-179.md

This UMIP introduces Across v3 and proposes updates to the ACROSS-V2 price identifier to support it.
As part of this change, UMIP-157 is marked for deprecation.

feat(across): Introduce UMIP-179 for Across v3

---

UMIPs/umip-179.md

This UMIP change adds references to Across Lite Chains.

feat(lite-chains): include definitions

---

UMIPs/umip-136.md

GitHub now supports defining these natively, delimited by $, $.
This was reported by John in the Across discord.

fix(umip-136): Restore tex formulas

---

UMIPs/umip-183.md

Changes proposed in this PR:
- Add UMIP 183: Add `MULTIPLE_VALUES` as a supported price identifier

feat: add umip 183

---

UMIPs/umip-136.md

This PR modifies the LP fee rate model equation to provide an upper bound at 100% of the deposit.

ENH: Modify LP fee equation

---

UMIPs/umip-179.md

Adds support for SVM chains, also fixing some interface inconsistencies for EVM

feat: svm support for across
