- UMIPs/umip-3.md
Since this is being voted on very soon, I think it makes sense for to move this directly to `Approved`.
This also fixes an error where the number of commits is misstated.
> Move UMIP-3 to Approved

- UMIPs/umip-xx.md
- clock time is used to define the range over which the gasUsed-weighted median is reported but the DVM imposes a minimum number of blocks within a given range (e.g. a minimum of 200 blocks to medianize over for the GASETH-1HR ticker)
- added 1W and 1M tickers
> use clock time with sanity minimums, plus 1W 1M tickers

- UMIPs/umip-16.md
- UMIPs/umip-17.md
Using a Google BigQuery query that @mrice32 created,  I have added another reference implementation. This will allow for flexibility in the actual usage of this price identifier. I also attempt to make it explicit that DVM reporters are free to define their own implementations of this calculation later, so long as those implementations agree with the calculation methodology.
> Updating GASETH UMIP with an additional calculation implementation

- UMIPs/umip-7.md
5 is not enough to express enough precision
> USDBTC should have 8 decimals of precision

- UMIPs/umip-28.md
As discussed with Matt and Nick offline.
> fix(umip-28) Clarify that stablespread should be denominated in ethusd 

- price-identifier-template.md
> Fix price-identifier template decimal example.

- UMIPs/umip-52.md
- UMIPs/umip-55.md
This adds UMIP-52, which proposes a DVM upgrade to add `ancillaryData` to the Voting and Oracle interfaces.
> Add UMIP-55

- UMIPs/umip-13.md
- UMIPs/umip-16.md
- UMIPs/umip-19.md
- UMIPs/umip-2.md
- UMIPs/umip-20.md
- UMIPs/umip-21.md
- UMIPs/umip-22.md
- UMIPs/umip-23.md
- UMIPs/umip-24.md
- UMIPs/umip-25.md
- UMIPs/umip-26.md
- UMIPs/umip-28.md
- UMIPs/umip-30.md
- UMIPs/umip-31.md
- UMIPs/umip-32.md
- UMIPs/umip-33.md
- UMIPs/umip-37.md
- UMIPs/umip-38.md
- UMIPs/umip-39.md
- UMIPs/umip-40.md
- UMIPs/umip-41.md
- UMIPs/umip-46.md
- UMIPs/umip-47.md
- UMIPs/umip-48.md
- UMIPs/umip-49.md
- UMIPs/umip-5.md
- UMIPs/umip-50.md
- UMIPs/umip-51.md
- UMIPs/umip-6.md
- UMIPs/umip-7.md
This PR does two things.
1. Adds a deprecation notice for any price identifier that is currently being used in a mainnet contract **AND** has a non-18 decimal scaling specification.
2. Edits all identifiers, that do not follow into the first category, to specify 18 decimals of scaling.
This is necessary because the new [EMP](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-54.md) and [Perp](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-53.md) require that all price identifiers be scaled to 18 decimals. Price identifiers that fall into the first category will resolve incorrectly if used with the new factories, hence the deprecation notices.
> Update price identifier decimals and deprecate legacy price IDs

- UMIPs/umip-26.md
- UMIPs/umip-29.md
- UMIPs/umip-32.md
As a result from the XAUPERL price request discussion on 02-26-21, a few corrections were identified as needed for FX price identifiers that use TraderMade. These corrections included:
- Using the open price of the OHLC period that the price request timestamp falls in, rather than the closing price. This is because the open price is technically closer to the price request timestamp than the open.
- Explicitly stating in all TraderMade UMIPs how to calculate a price for a time that falls outside of FX market hours.
- Removing any rounding for intermediary calculation steps.
> Update TraderMade Price Identifiers

- UMIPs/umip-22.md
This PR updates the unused GASETH-TWAP-1Mx1M price id to allow it to be used again for future contracts. Other than small nit corrections, only the used timestamp is changed.
> Update timestamp on GASETH-TWAP-1Mx1M to make it usable

- UMIPs/umip-draft_domfi_alts.md
Hey all,
This UMIP proposal adds 9 additional market dominance price identifiers that are currently supported by CoinGecko.
Let us know your feedback or any questions you have regarding the UMIP.
Thanks!
~ Domination Finance Team
> Add BCHDOM, BNBDOM, BSVDOM, DOTDOM, ETHDOM, LINKDOM, LTCDOM, USDTDOM & XRPDOM as price identifiers

- UMIPs/umip-32.md
The CNYUSD price from Tradermade is only ever returned to 5 decimals. There was an oversight in the UMIP where rounding was specified to 6 decimals. Although this would have no affect on the actual returned price, it seems best to update this UMIP to avoid any confusion.
> Update CNYUSD UMIP rounding spec

- UMIPs/umip-46.md
This update does 3 things:
1. Removes Bittrex OCEAN/USDT in favor of Kraken OCEAN/USD
2. Updates the rounding spec of USDOCEAN from 18 decimals to 6 decimals
3. Clarifies that rounding should not happen in intermediate steps for USDOCEAN
See the discussion in the UMA Discord `voting` channel for more details
> Update USDOCEAN price identifier based upon lessons learned in voting

- UMIPs/umip-6.md
Updating the USDETH price identifier to round to more decimal places has been discussed multiple times during voting. This PR makes that change.
Couple of examples of discussions and consensus around this change:
- [Discussion 1](https://discord.com/channels/718590743446290492/719352532354465833/845293636961697912)
- [Discussion 2](https://discord.com/channels/718590743446290492/719352532354465833/827211957571420191)
> Update USDETH rounding spec to 8 decimals based on community feedback

- UMIPs/umip-40.md
As discussed with Sean, making corresponding changes to update the 3M px identifier futures' dates to 0924
> Updating 3M basis futures' dates to 0924

- UMIPs/umip-108.md
This PR updates the gas price umip in order to account for the changes to the ethereum gas fee market made by EIP-1559. Specifically it changes a few references from using the gas price of a transaction to using the effective gas price, which accounts for both the old and new transaction format
> Updates umip-108 to reflect gas fee market changes made by EIP-1559

- Implementations/bankless-legal-guild.md
In order not to over-complicate the ancillary data parsing module better to use just straight quotation marks for escaping values with delimiters (: or ,)
> Fix to straight quotation marks

- Add DFX Polygon.md
- UMIPs/umip-104.md
The DFX token has already been passed in UMIP 104: https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-104.md
This UPP is here to add the DFX Polygon token to list of approved collaterals
> Add DFX Polygon token

- UMIPs/umip-136.md
@cc7768 I think this is also missing in some of our other docs. We should decide what these params should be. In the bots we've been assuming that they're all 100%, so that's what I specified here.
Edit: I'm dumb. Fooled by the scrollbar.
> fix: add r2 param

- UMIPs/DRAFT_SKINNY_OO.md
- UMIPs/umip-135.md
The UMIP doesn't need to be changed but the contract includes some important improvements found after an external audit with OpenZeppelin:
- `proposePriceFor` call back was incorrectly made to `msg.sender` instead of `requester`, [PR](https://github.com/UMAprotocol/protocol/pull/3531). 
- `bond` amount in `requestAndProposePriceFor` should default to `finalFee` similar to `requestPrice`, [PR](https://github.com/UMAprotocol/protocol/pull/3534)
- `requestAndProposePriceFor` should be reentrancy guarded, [PR](https://github.com/UMAprotocol/protocol/pull/3539)
> improve(umip-135): Change SkinnyOptimisticOracle to new address

- UPPs/upp-10.md
- UPPs/upp-8.md
- UPPs/upp-9.md
This fix does not change final fees thus not requiring governance vote, but it does clarify the Rationale section in mathematically correct way as pointed out by the community.
> Fix percentage notion in Rationale of UPPs8-10

- UMIPs/umip-proposer.md
Adds an UMIP to approve the Proposer contract to request and retrieve prices from the DVM.
> Approve Proposer contract to interact with DVM

- Implementations/zodiac.md
Signed-off-by: John Shutt <pemulis@users.noreply.github.com>
This is the first draft of a UMIP to add a `ZODIAC` identifier that would allow the Optimistic Oracle to enforce a set of natural language off-chain rules governing a Gnosis Safe, allowing flexible and powerful "optimistic governance" for the first time.
> Add ZODIAC as price identifier

- UMIPs/umip-152.md
After working on this for a bit, I'd like to reconfigure the ancillary data to go: `explanation: here's an explanation,id:123,module:0xabc...123`. This removes the rules and adds the Zodiac module contract address.
Some rationale:
1. The rules can be found at the module address and the ones submitted with the price request may not be valid at the time of consideration since rules can be changed by other mechanisms explained in the UMIP.
2. If the rules are represented by an IPFS hash, as desired, that's easier to handle internally with a string or bytes rather than bytes32, but that makes it much harder to append to ancillary data.
3. Including the address of the module should make it easier to figure out what's going on and find the relevant rules.
4. Having the explanation first lets …
> fix: update ancillary data specification

- UMIPs/FDT Collateral Adds.md
- UMIPs/VSQ & FDT Collateral Adds.md
Initial research shows the VESQ contract deployed solely on Polygon & FDT solely on Ethereum Mainnet.
> Create VSQ & FDT Collateral Adds.md

- Implementations/suTVL-KPI.md
The current version denominates values in ETH by converting the collateral prices to ETH. Realizing it might be easier to change this to USD and do a separate step for getting the ETH price so that it will be easier to use the defillama adapter when this expires. Let me know if you agree.
> suTVL implementation doc

- UMIPs/umip-152.md
Signed-off-by: John Shutt <pemulis@users.noreply.github.com>
This pull request updates UMIP-152 for the `ZODIAC` identifier to better reflect the revised contract code, proposal/dispute/execution/deletion flows, and some additional considerations around the use of transitional administrative multi-sigs that can delete proposals in the event of an emergency.
> docs: update umip-152 based on audit feedback

- UMIPs/umip-161.md
- UMIPs/umip-162.md
Signed-off-by: Pablo Maldonado <pablo@umaproject.org>
UMIP-162 optional callbacks and event-based requests
> This UMIP will result in the creation of a new optimistic oracle contract with enhanced control over pricing request callbacks, which will only be executed if the requester has declared its readiness to receive them. This modification also eliminates the use of try-catch structures, which were vulnerable to gas griefing. Additionally, the contract includes a new event-based price request, which is suitable for requests that depend on events without a fixed date, thereby evaluating pricing requests at the time of proposal. This will enable the implementation of a more robust and adaptable price requests.
> Add umip162 optional callbacks and event-based requests

- UMIPs/umip-157.md
This UMIP should be paired with https://github.com/across-protocol/relayer-v2/pull/301 to add a way to configure spoke target balances in Across v2.
> feat: add target balance configuration

- UMIPs/umip-157.md
Allows admin to set rate models per deposit path, increasing system's capital efficiency by charging more dynamic fees
> feat: Add update about deposit-path specific "route rate models"

- UMIPs/umip-169.md
- UMIPs/umip-oa.md
Signed-off-by: Pablo Maldonado <pablo@umaproject.org>
Changes proposed in this PR:
Add UMIP to register the Optimistic Asserter in the Registry and Finder in the following networks:
- Mainnet: [0xFEc7C6AA64fDD17f456028e0B411f5c3877ADa5e](https://etherscan.io/address/0xFEc7C6AA64fDD17f456028e0B411f5c3877ADa5e)
- Polygon: [0x1a3cF7c0f99256431Fd6e8163FF8748A4aE50b6F](https://polygonscan.com/address/0x1a3cF7c0f99256431Fd6e8163FF8748A4aE50b6F)
- Optimism: [0xCd5FE81278FEbf3a9323eFC9F68AEcCAeAE8BE2C](https://optimistic.etherscan.io/address/0xCd5FE81278FEbf3a9323eFC9F68AEcCAeAE8BE2C)
- Arbitrum: [0x211AD7adEf4d4348408B43da49D99bA117ADD8D1](https://arbiscan.io/address/0x211AD7adEf4d4348408B43da49D99bA117ADD8D1)
- Boba: [0x17d02b5CDb6fe2c681A447B119e9f6F5AB4E3018](https://bobascan.com/address/0x17d …
> feat: add optimistic asserter umip

- UMIPs/umip-170.md
With the Update OptimisticOracleV3 in [UMIP-172](https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-172.md) `ASSERT_TRUTH` identifier should be updated to be compatable with new naming.
> fix: update-umip-170

- UMIPs/umip-132.md
- UMIPs/umip-176.md
Changes proposed in this PR:
Update the `SHERLOCK_CLAIM` price identifier to align with the [SherlockClaimManager](https://github.com/sherlock-protocol/sherlock-v2-core/blob/main/contracts/managers/SherlockClaimManager.sol#L605) implementation.
- Change the `approve` value from 1 to `claim.value`
- Remove the `unresolvable` = `0.5` return option
> feat: update sherlock identifier to align with contract implementation

- UMIPs/umip-157.md
Long standing change to move CHAIN_ID list to config store rather than enshrined only in UMIP
> feat: Add CHAIN_ID_INDICES to config store

- UMIPs/umip-178.md
This UMIP proposes to accept the Across Bond Token (ABT) as collateral
within the UMA ecosystem. ABT will be used by Across to limit the set of
addresses that are able to make root bundle proposals to the Across
HubPool contract.
> feat: Propose Across Bond Token for use as collateral

- UMIPs/umip-157.md
Deprecated and replaced by `spokeTargetBalances` which achieves the same goal of allowing the protocol to keep excess funds on spoke pool balances in a more nuanced way
> feat(umip157): Remove `transferThreshold` from Across parameters

- UMIPs/umip-182.md
Proposes UMIP-182 to register Blast Parent Messenger in OracleHub and GovernorHub
> feat: register blast parent messenger

- UMIPs/umip-179.md
These deposits never utilize any LP funds so they should be charged a 0% LP fee. In practice this is what happens but we should add it to the protocol
> improve(179): Add caveat about lp fee = 0% when originChain == repaymentChain
